### ISSUE TITLE
The Status text is in the wrong place for some subjects when marked as 'Maybe'.

### ISSUE THREAD

**Issue by HanadS** [SIMEXP/dashQC_fmri#8] opened 2018-10-29 18:35 UTC
This is how it should look. 
![image](https://user-images.githubusercontent.com/26352860/47678397-16de9d00-db98-11e8-870a-d86c8756d2c2.png)
 

This is what I sometimes see. 
![image](https://user-images.githubusercontent.com/26352860/47678419-278f1300-db98-11e8-9e7c-3a7af352283d.png)

**Comment by jarmoza** [comment] 2018-11-14 16:33
Suggested fix: This is likely an issue with Bootstrap. Move status label inside of structure that prevents it from being shifted around separately by different browser window sizes.

**Comment by jarmoza** [comment] 2019-07-31 15:30
Currently unable to reproduce this error. May have been fixed in a previous release. Closing for now.

**Closed by jarmoza** 2019-07-31 15:30 UTC
Labels: bug
